-- scripts/seed.mjs로 생성합니다. 기존 운영 데이터는 덮어쓰지 않습니다.
insert into public.ingredients values
('seaweed','김','김','fixed',0,null,0),
('rice','밥','밥','fixed',1,null,0),
('egg','계란','EGG','base',2,null,0),
('ham','햄','HAM','base',3,null,0),
('radish','단무지','단무지','base',4,null,0),
('crab','맛살','CRAB STICK','base',5,null,0),
('pork','제주 돼지고기','PORK','topping',6,'/brand/ingredients/pork.svg',3000),
('turban-shell','뿔소라','TURBAN SHELL','topping',7,'/brand/ingredients/turban-shell.svg',3000),
('fernbrake','고사리','FERNBRAKE','topping',8,'/brand/ingredients/fernbrake.svg',3000),
('carrot','당근','CARROT','topping',9,'/brand/ingredients/carrot.svg',3000) on conflict do nothing;
insert into public.inventory(ingredient_id) select id from public.ingredients where kind='topping' on conflict do nothing;
insert into public.products values
('gimbap','기본 김밥','base',5000,true),
('package','라면 · 음료 · 굿즈 패키지','upgrade',10000,true),
('ramen','라면','extra',null,false),
('drink','음료','extra',null,false),
('goods','굿즈','extra',null,false) on conflict do nothing;
insert into public.survey_versions values ('draft-v2','[{"id":"S1","title":"어디에서 오셨나요?","type":"single","required":true,"options":[{"id":"kr","label":"한국"},{"id":"jp","label":"일본"},{"id":"cn","label":"중국"},{"id":"tw","label":"대만"},{"id":"hk","label":"홍콩·마카오"},{"id":"sea","label":"동남아시아"},{"id":"na","label":"미국·캐나다"},{"id":"eu","label":"유럽"},{"id":"other","label":"기타"}]},{"id":"S2","title":"연령대를 알려주세요","type":"single","required":true,"options":[{"id":"10","label":"10대 이하"},{"id":"20","label":"20대"},{"id":"30","label":"30대"},{"id":"40","label":"40대"},{"id":"50","label":"50대"},{"id":"60","label":"60대 이상"}]},{"id":"S3","title":"성별을 알려주세요","type":"single","required":false,"options":[{"id":"female","label":"여성"},{"id":"male","label":"남성"},{"id":"none","label":"응답하지 않음"}]},{"id":"S4","title":"새로운 음식에 얼마나 열려 있나요?","type":"single","required":true,"options":[{"id":"familiar","label":"익숙한 맛이 좋아요"},{"id":"open","label":"적당히 열려 있어요"},{"id":"adventurous","label":"새로운 맛에 적극적이에요"}]},{"id":"S5","title":"가장 끌리는 제주 원물은 무엇인가요?","type":"single","required":true,"options":[{"id":"vegetable","label":"채소"},{"id":"seafood","label":"해산물"},{"id":"meat","label":"육류"},{"id":"all","label":"골고루"}]},{"id":"S6","title":"좋아하는 식감은 무엇인가요?","type":"single","required":true,"options":[{"id":"crunchy","label":"아삭한 것"},{"id":"soft","label":"부드러운 것"},{"id":"chewy","label":"쫄깃한 것"},{"id":"all","label":"골고루"}]},{"id":"S7","title":"음식을 고를 때 가장 중요한 것은?","type":"single","required":true,"options":[{"id":"taste","label":"맛"},{"id":"health","label":"건강"},{"id":"jeju","label":"제주다움"},{"id":"story","label":"이야기"}]},{"id":"S8","title":"먹지 못하거나 피하고 싶은 재료가 있나요?","type":"multiple","required":true,"options":[{"id":"egg","label":"계란","linkedIngredientId":"egg"},{"id":"ham","label":"햄","linkedIngredientId":"ham"},{"id":"crab","label":"맛살","linkedIngredientId":"crab"},{"id":"pork","label":"제주 돼지고기","linkedIngredientId":"pork"},{"id":"turban-shell","label":"뿔소라","linkedIngredientId":"turban-shell"},{"id":"fernbrake","label":"고사리","linkedIngredientId":"fernbrake"},{"id":"carrot","label":"당근","linkedIngredientId":"carrot"},{"id":"none","label":"해당 없음","exclusive":true}]}]'::jsonb,not exists(select 1 from public.survey_versions where active)) on conflict do nothing;
insert into public.contents(id,language,title) values
('usage','ko',''),
('brand','ko',''),
('producer','ko',''),
('consent','ko',''),
('experience','ko',''),
('pork','ko',''),
('turban-shell','ko',''),
('fernbrake','ko',''),
('carrot','ko',''),
('usage','en',''),
('brand','en',''),
('producer','en',''),
('consent','en',''),
('experience','en',''),
('pork','en',''),
('turban-shell','en',''),
('fernbrake','en',''),
('carrot','en',''),
('usage','ja',''),
('brand','ja',''),
('producer','ja',''),
('consent','ja',''),
('experience','ja',''),
('pork','ja',''),
('turban-shell','ja',''),
('fernbrake','ja',''),
('carrot','ja',''),
('usage','zh',''),
('brand','zh',''),
('producer','zh',''),
('consent','zh',''),
('experience','zh',''),
('pork','zh',''),
('turban-shell','zh',''),
('fernbrake','zh',''),
('carrot','zh','') on conflict do nothing;
